### ISSUE TITLE
Source exceeds 132 column

### ISSUE THREAD

**Issue by szaghi** [victorsndvg/ForEx#2]
Hi @victorsndvg ,

your nightmare becomes reality... I am testing ForEx!

My first compilation give me an error (a warning for all normal people): some statements exceed the 132 column, e.g.

``` shell
Building ./src/tests/Exception_test.f90
Compiling ./src/lib/Exception.f90 serially
./src/lib/Exception.f90:149:132:

             Write(unit=unitd,fmt=*, iostat=iostatd, iomsg=iomsgd) 'throwed in File: '//trim(adjustl(ch))//')'
                                                                                                            1
Error: Line truncated at (1) [-Werror=line-truncation]
```

As said, this is not really an error, but I like to pointing it out.

See you soon.

**Comment by szaghi** [comment]
I just see the macro defined into `ExceptionHandler.i90`... ok I am trimming out my OCD and allow to exceed the 132 column :smile: 

It is very frustrating the pre-processing limits of Fortran/cpp.

See you soon.

**Comment by victorsndvg** [comment]
Thanks @szaghi !

I'm very glad (and afraid :laughing: )to know that you're testin it! I really appreciate all your comments!

I've cutted some lines in the f90 files. I think that the macro could be obfuscated in the future, but now I prefer to keep it readable.

Let me know your likes, dislikes, suggestions ... about ForEx!
Thanks again!

**Comment by szaghi** [comment]
Hi @victorsndvg 

The result is very impressive, the code is not easy to understand for me :cry: 

For the moment, I still cannot figure out how use it into one of me _real-day-stuff_, but this is only the first read.

**Comment by szaghi** [comment]
@victorsndvg 

Just a note: in my fork I added a simple fobos for building by FoBiS in the case you are interested into it.

**Comment by victorsndvg** [comment]
@szaghi 

`ExceptionHandler.i90` it's a little bit complicated... and of course it can be improved!
I can answer you any doubt about the code, the design, some decisions ... Feel free to ask!

I didn't use FoBis, but someone could be interested in you compilation system. I will be happy to accept a merge request with your changes!
